<?php
session_start();
unset($_SESSION['email']);
unset($_SESSION['phone_number']);
unset($_SESSION['id']);
unset($_SESSION['first_name']);
unset($_SESSION['last_name']);
unset($_SESSION['phone_number']);
unset($_SESSION['email']);
unset($_SESSION['branch_id']);
unset($_SESSION['provinceName']);
session_destroy();
header("location:login.php");
exit();
?>